Output out.gif

Set FontSize 26
Set Height 825
Set Width 1000
Set Padding 10
Set Margin 30
Set MarginFill "#0C1015"
Set BorderRadius 8
Set WindowBar Colorful

Hide
Type "gambit"
Enter
Show

Type "e2"
Sleep 1
Type "e4"
Sleep 1
Type "e7"
Sleep 1
Type "e5"
Sleep 1
Type "g1"
Sleep 1
Type "f3"
Sleep 1
Type "b8"
Sleep 1
Type "c6"
Sleep 1
Type "f1"
Sleep 1
Type "b5"
Sleep 1
Type "g8"
Sleep 1
Type "f6"
Sleep 1
Type "e1"
Sleep 1
Type "g1"

Sleep 3
