version: "3.1"
services:
  soft-serve:
    image: ghcr.io/maaslalani/gambit:latest
    container_name: gambit
    volumes:
      - ./data:/data
    ports:
      - 53531:53531
    environment:
      - GAMBIT_SERVER_HOST=
      - GAMBIT_SERVER_PORT=53531
      - GAMBIT_SERVER_KEY_PATH="/data/gambit"
    command: serve
    restart: unless-stopped